[workspace]
members = [
    "crates/metal-api-core",
    "crates/metal-api-reims-vulkan",
    "crates/metal-api-vulkan",
    "examples/metal-smoke",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.87"
publish = false

[workspace.dependencies]
ash = { version = "0.38", default-features = false, features = ["loaded"] }
metal2vulkan = { git = "https://github.com/steelbrain/metal2vulkan.git", rev = "9e0e99a41dc3cb8bb7e288b531f1698a79fd4b1c" }
spirv = "0.4"

[profile.release]
lto = "thin"
codegen-units = 1
